### ISSUE TITLE
Problem with 'consolidation' dependency

### ISSUE THREAD

**Issue by dphiffer** [pantheon-systems/terminus-installer#42]
If your issue is being submitted to report a bug, please also include the following:

1. The name and version of your OS: Ubuntu 16.04.2
2. The name and version of your terminal client: Terminal.app 2.9.5 (421.2)
3. Which version of PHP you are using: PHP 7.0.33-0ubuntu0.16.04.6 (cli) ( NTS )
4. All relevant Terminal text:

Trying to install and run `terminus`:

```
$ curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 3349k  100 3349k    0     0  6189k      0 --:--:-- --:--:-- --:--:-- 6192k
Installing Terminus...
Using version ^2.0 for pantheon-systems/terminus
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 35 installs, 0 updates, 0 removals
    <warning>Failed to download symfony/polyfill-ctype from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/polyfill-ctype (v1.12.0): Cloning 550ebaac28 from cache
    <warning>Failed to download symfony/yaml from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/yaml (v3.4.31): Cloning 3dc414b7db from cache
    <warning>Failed to download symfony/process from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/process (v3.4.31): Cloning d822cb6540 from cache
    <warning>Failed to download symfony/finder from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/finder (v3.4.31): Cloning 1fcad80b44 from cache
    <warning>Failed to download psr/log from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing psr/log (1.1.0): Cloning 6c001f1daa from cache
    <warning>Failed to download symfony/debug from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/debug (v3.4.31): Cloning 0b60030091 from cache
    <warning>Failed to download symfony/polyfill-mbstring from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/polyfill-mbstring (v1.12.0): Cloning b42a2f66e8 from cache
    <warning>Failed to download symfony/console from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/console (v3.4.31): Cloning 4510f04e70 from cache
    <warning>Failed to download jakub-onderka/php-console-color from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing jakub-onderka/php-console-color (v0.2): Cloning d5deaecff5 from cache
    <warning>Failed to download jakub-onderka/php-console-highlighter from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Cloning 7daa75df45 from cache
    <warning>Failed to download dnoegel/php-xdg-base-dir from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing dnoegel/php-xdg-base-dir (0.1): Cloning 265b859349 from cache
    <warning>Failed to download nikic/php-parser from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing nikic/php-parser (v3.1.5): Cloning bb87e28e7d from cache
    <warning>Failed to download symfony/var-dumper from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/var-dumper (v3.4.31): Cloning 5408ad7194 from cache
    <warning>Failed to download psr/container from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing psr/container (1.0.0): Cloning b7ce3b1764 from cache
    <warning>Failed to download psy/psysh from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing psy/psysh (v0.8.18): Cloning 5357b1cffc from cache
    <warning>Failed to download guzzlehttp/promises from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing guzzlehttp/promises (v1.3.1): Cloning a59da6cf61 from cache
    <warning>Failed to download ralouphie/getallheaders from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing ralouphie/getallheaders (3.0.3): Cloning 120b605dfe from cache
    <warning>Failed to download psr/http-message from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing psr/http-message (1.0.1): Cloning f6561bf28d from cache
    <warning>Failed to download guzzlehttp/psr7 from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing guzzlehttp/psr7 (1.6.1): Cloning 239400de7a from cache
    <warning>Failed to download guzzlehttp/guzzle from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing guzzlehttp/guzzle (6.3.3): Cloning 407b0cb880 from cache
    <warning>Failed to download symfony/event-dispatcher from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/event-dispatcher (v3.4.31): Cloning 3e922c4c34 from cache
    <warning>Failed to download symfony/filesystem from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing symfony/filesystem (v3.4.31): Cloning 00e3a6ddd7 from cache
    <warning>Failed to download dflydev/dot-access-data from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing dflydev/dot-access-data (v1.1.0): Cloning 3fbd874921 from cache
    <warning>Failed to download grasmash/yaml-expander from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing grasmash/yaml-expander (1.4.0): Cloning 3f0f6001ae from cache
    <warning>Failed to download consolidation/self-update from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing consolidation/self-update (1.1.5): Cloning a1c273b14c from cache
    <warning>Failed to download consolidation/output-formatters from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing consolidation/output-formatters (3.5.0): Cloning 99ec998ffb from cache
    <warning>Failed to download consolidation/annotated-command from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing consolidation/annotated-command (2.12.0): Cloning 512a2e54c9 from cache
    <warning>Failed to download grasmash/expander from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing grasmash/expander (1.0.0): Cloning 95d6037344 from cache
    <warning>Failed to download consolidation/config from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing consolidation/config (1.2.1): Cloning cac1279bae from cache
    <warning>Failed to download consolidation/log from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing consolidation/log (1.1.1): Cloning b2e887325e from cache
    <warning>Failed to download container-interop/container-interop from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing container-interop/container-interop (1.2.0): Cloning 79cbf1341c from cache
    <warning>Failed to download league/container from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing league/container (2.4.1): Cloning 43f35abd03 from cache
    <warning>Failed to download consolidation/robo from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing consolidation/robo (1.4.10): Cloning e5a6ca64cf from cache
    <warning>Failed to download composer/semver from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing composer/semver (1.5.0): Cloning 46d9139568 from cache
    <warning>Failed to download pantheon-systems/terminus from dist: The zip extension and unzip command are both missing, skipping.
Your command-line PHP is using multiple ini files. Run `php --ini` to show them.</warning>
    <warning>Now trying to download from source</warning>
  - Installing pantheon-systems/terminus (2.0.1): Cloning 123e99efdb from cache
symfony/polyfill-mbstring suggests installing ext-mbstring (For best performance)
symfony/console suggests installing symfony/lock
symfony/var-dumper suggests installing ext-intl (To show region name in time zone dump)
symfony/var-dumper suggests installing ext-symfony_debug
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
guzzlehttp/psr7 suggests installing zendframework/zend-httphandlerrunner (Emit PSR-7 responses)
symfony/event-dispatcher suggests installing symfony/dependency-injection
symfony/event-dispatcher suggests installing symfony/http-kernel
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
Writing lock file
Generating autoload files
Terminus was installed, but the installer was not able to write to your bin dir. To enable the 
`terminus` command, add this alias to your .bash_profile (Mac) or .bashrc (Linux) file:

alias terminus=/home/ubuntu/vendor/bin/terminus

Or you can enable it by adding the directory the executable file is in to your path:

PATH="/home/ubuntu/vendor/bin:$PATH"
$ alias terminus=/home/ubuntu/vendor/bin/terminus
$ terminus
PHP Fatal error:  Uncaught ReflectionException: Class DOMDocument does not exist in /home/ubuntu/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php:24
Stack trace:
#0 /home/ubuntu/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php(24): ReflectionClass->isSubclassOf('DOMDocument')
#1 /home/ubuntu/vendor/consolidation/output-formatters/src/FormatterManager.php(372): Consolidation\OutputFormatters\Transformations\DomToArraySimplifier->canSimplify(Object(ReflectionClass))
#2 /home/ubuntu/vendor/consolidation/output-formatters/src/FormatterManager.php(194): Consolidation\OutputFormatters\FormatterManager->canSimplifyToArray(Object(ReflectionClass))
#3 /home/ubuntu/vendor/consolidation/output-formatters/src/FormatterManager.php(189): Consolidation\OutputFormatters\FormatterManager->isValidDataType(Object(Consolidation\OutputFormatters\Formatters\NoOutputFormatter), Object(ReflectionClass))
#4 /home/ubuntu/vendor/consolidation/output-formatters/src/FormatterManager.php in /home/ubuntu/vendor/consolidation/output-formatters/src/Transformations/DomToArraySimplifier.php on line 24
```

**Comment by dphiffer** [comment]
Never mind! I needed to install `php-xml`.
