### ISSUE TITLE
Fail to install terminus

### ISSUE THREAD

**Issue by rhizomenet** [pantheon-systems/terminus-installer#49]
If your issue is being submitted to report a bug, please also include the following:

1. Windows 10
2. GNU bash, version 4.3.42(5)-release (x86_64-pc-msys)  - Git Bash
3. php 7.4.11

I am running these three commands

$ curl -L https://github.com/pantheon-systems/terminus/releases/download/3.0.6/terminus.phar --output terminus
$ chmod +x terminus
$ ./terminus self:update

The file download correctly and execute permissions granted.
Then running terminus command I am getting this error, as if some argument is missing   when constructing the internal program

`
Fatal error: Uncaught TypeError: Argument 2 passed to Symfony\Component\Console\Application::__construct() must be of the type string, null given, called in phar://D:/terminus_3.0.6/terminus/src/Terminus.php on line 87 and defined in phar://D:/terminus_3.0.6/terminus/vendor/symfony/console/Application.php:91
Stack trace:
#0 phar://D:/terminus_3.0.6/terminus/src/Terminus.php(87): Symfony\Component\Console\Application->__construct('Terminus', NULL)
#1 phar://D:/terminus_3.0.6/terminus/src/Terminus.php(567): Pantheon\Terminus\Terminus->__construct(Object(Pantheon\Terminus\Config\DefaultsConfig), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar://D:/terminus_3.0.6/terminus/bin/terminus(77): Pantheon\Terminus\Terminus::factory('617a5343ca')
#3 D:\terminus_3.0.6\terminus(12): require('phar://D:/termi...')
#4 {main}
  thrown in phar://D:/terminus_3.0.6/terminus/vendor/symfony/console/Application.php on line 91

`

**Comment by albanyacademy** [comment]
having the same issue - did you figure out what happened?

**Comment by rhizomenet** [comment]
I am using terminus on WSL2  that let you run Linux shell on Windows

https://learn.microsoft.com/en-us/windows/wsl/install
